export { default as About } from './About/About';
export { default as Brands } from './Admin/Brands/Brands';
export { default as SingleBrand } from './Admin/Brands/SingleBrand';
export { default as AddEditForm } from './Admin/CategoriesAdmin/AddEditForm/AddEditForm';
export { default as SingleCategoryAdmin } from './Admin/CategoriesAdmin/SingleCategoryAdmin/SingleCategoryAdmin';
export { default as CategoriesAdmin } from './Admin/CategoriesAdmin/CategoriesAdmin';
export { default as ConfirmDeleteCategory } from './Admin/CategoriesAdmin/ConfirmDeleteCategory';
export { default as HeaderAdmin } from './Admin/HeaderAdmin/HeaderAdmin';
export { default as SearchBarAdmin } from './Admin/HeaderAdmin/SearchBarAdmin';
export { default as Login } from './Admin/Login/Login';
export { default as ConfirmDeleteOrder } from './Admin/Orders/ConfirmDeleteOrder/ConfirmDeleteOrder';
export { default as SingleOrder } from './Admin/Orders/SingleOrder/SingleOrder';
export { default as Orders } from './Admin/Orders/Orders';
export { default as MainAdmin } from './Admin/MainAdmin';
export { default as ProductsAdmin } from './Admin/ProductsAdmin/ProductsAdmin';
export { default as ProductCard } from './Admin/ProductsAdmin/ProductCard/ProductCard';
export { default as ProductEditForm } from './Admin/ProductsAdmin/ProductEditForm/ProductEditForm';
export { default as SliderAdmin } from './Admin/Slider/Slider';
export { default as SlideEditForm } from './Admin/Slider/SlideEditForm/SlideEditForm';
export { default as ConfirmDeleteSlide } from './Admin/Slider/ConfirmDeleteSlide';
export { default as Slide } from './Admin/Slider/Slide';
export { default as SearchAdmin } from './Admin/SearchAdmin/SearchAdmin';
export { default as AdminLayout } from './Admin/AdminLayout';


export { default as Cart } from './Cart/Cart';
export { default as CartIcon } from './Header/CartIcon';
export { default as CartItem } from './CartItem/CartItem';
export { default as Category } from './Category/Category';
export { default as BrandSelector } from './Category/BrandSelector/BrandSelector';
export { default as Contacts } from './Contacts/Contacts';
export { default as Footer } from './Footer/Footer';
export { default as Header } from './Header/Header';
export { default as ItemCard } from './ItemCard/ItemCard';
export { default as ItemDetails } from './ItemDetails/ItemDetails';
export { default as ShowPicture } from './ItemDetails/ShowPicture';
export { default as Layout } from './Layout/Layout';
export { default as Loader } from './Loader/Loader';
export { default as Main } from './Main/Main';
export { default as NoMatch } from './NoMatch/NoMatch';
export { default as OrderForm } from './OrderForm/OrderForm';
export { default as CompleteOrder } from './OrderForm/CompleteOrder';
export { default as Search } from './Search/Search';
export { default as SearchIcon } from './Header/SearchIcon';
export { default as SearchBar } from './SearchBar/SearchBar';
export { default as Slider } from './Slider/Slider';

export * from './NoMatch/NoMatch';
export * from './Contacts/Contacts';